## clk
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

## seg_flag
set_property PACKAGE_PIN G2 [get_ports {seg_flag[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[7]}]
set_property PACKAGE_PIN C2 [get_ports {seg_flag[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[6]}]
set_property PACKAGE_PIN C1 [get_ports {seg_flag[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[5]}]
set_property PACKAGE_PIN H1 [get_ports {seg_flag[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[4]}]
set_property PACKAGE_PIN G1 [get_ports {seg_flag[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[3]}]
set_property PACKAGE_PIN F1 [get_ports {seg_flag[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[2]}]
set_property PACKAGE_PIN E1 [get_ports {seg_flag[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[1]}]
set_property PACKAGE_PIN G6 [get_ports {seg_flag[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_flag[0]}]

## seg0
set_property PACKAGE_PIN B4 [get_ports {seg0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[7]}]
set_property PACKAGE_PIN A4 [get_ports {seg0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[6]}]
set_property PACKAGE_PIN A3 [get_ports {seg0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[5]}]
set_property PACKAGE_PIN B1 [get_ports {seg0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[4]}]
set_property PACKAGE_PIN A1 [get_ports {seg0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[3]}]
set_property PACKAGE_PIN B3 [get_ports {seg0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[2]}]
set_property PACKAGE_PIN B2 [get_ports {seg0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[1]}]
set_property PACKAGE_PIN D5 [get_ports {seg0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg0[0]}]

# seg1
set_property PACKAGE_PIN D4 [get_ports {seg1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[7]}]
set_property PACKAGE_PIN E3 [get_ports {seg1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[6]}]
set_property PACKAGE_PIN D3 [get_ports {seg1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[5]}]
set_property PACKAGE_PIN F4 [get_ports {seg1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[4]}]
set_property PACKAGE_PIN F3 [get_ports {seg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[3]}]
set_property PACKAGE_PIN E2 [get_ports {seg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[2]}]
set_property PACKAGE_PIN D2 [get_ports {seg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[1]}]
set_property PACKAGE_PIN H2 [get_ports {seg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[0]}]

## button
set_property PACKAGE_PIN U4 [get_ports {btn_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[4]}]
set_property PACKAGE_PIN V1 [get_ports {btn_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[3]}]
set_property PACKAGE_PIN R15 [get_ports {btn_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[2]}]
set_property PACKAGE_PIN R17 [get_ports {btn_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[1]}]
set_property PACKAGE_PIN R11 [get_ports {btn_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[0]}]

## reset button
set_property PACKAGE_PIN P15 [get_ports {btn_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_in[5]}]

## LED0 left
set_property PACKAGE_PIN F6 [get_ports {LED0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[7]}]
set_property PACKAGE_PIN G4 [get_ports {LED0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[6]}]
set_property PACKAGE_PIN G3 [get_ports {LED0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[5]}]
set_property PACKAGE_PIN J4 [get_ports {LED0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[4]}]
set_property PACKAGE_PIN H4 [get_ports {LED0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[3]}]
set_property PACKAGE_PIN J3 [get_ports {LED0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[2]}]
set_property PACKAGE_PIN J2 [get_ports {LED0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[1]}]
set_property PACKAGE_PIN K2 [get_ports {LED0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED0[0]}]

## LED1 right
set_property PACKAGE_PIN K1 [get_ports {LED1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[7]}]
set_property PACKAGE_PIN H6 [get_ports {LED1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[6]}]
set_property PACKAGE_PIN H5 [get_ports {LED1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[5]}]
set_property PACKAGE_PIN J5 [get_ports {LED1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[4]}]
set_property PACKAGE_PIN K6 [get_ports {LED1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[3]}]
set_property PACKAGE_PIN L1 [get_ports {LED1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[2]}]
set_property PACKAGE_PIN M1 [get_ports {LED1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[1]}]
set_property PACKAGE_PIN K3 [get_ports {LED1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED1[0]}]

## switch
set_property PACKAGE_PIN R1 [get_ports {switch[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[7]}]
set_property PACKAGE_PIN N4 [get_ports {switch[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[6]}]
set_property PACKAGE_PIN M4 [get_ports {switch[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[5]}]
set_property PACKAGE_PIN R2 [get_ports {switch[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[4]}]
set_property PACKAGE_PIN P2 [get_ports {switch[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[3]}]
set_property PACKAGE_PIN P3 [get_ports {switch[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[2]}]
set_property PACKAGE_PIN P4 [get_ports {switch[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[1]}]
set_property PACKAGE_PIN P5 [get_ports {switch[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[0]}]

## ADC config
set_property PACKAGE_PIN R5 [get_ports {DAC_ILE}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_ILE}]
set_property PACKAGE_PIN N6 [get_ports {DAC_CS}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_CS}]
set_property PACKAGE_PIN V6 [get_ports {DAC_WR1}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_WR1}]
set_property PACKAGE_PIN R6 [get_ports {DAC_WR2}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_WR2}]
set_property PACKAGE_PIN V7 [get_ports {DAC_XFER}]
set_property IOSTANDARD LVCMOS33 [get_ports {DAC_XFER}]

## ADC data
set_property PACKAGE_PIN U9 [get_ports {toDAC[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[7]}]
set_property PACKAGE_PIN V9 [get_ports {toDAC[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[6]}]
set_property PACKAGE_PIN U7 [get_ports {toDAC[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[5]}]
set_property PACKAGE_PIN U6 [get_ports {toDAC[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[4]}]
set_property PACKAGE_PIN R7 [get_ports {toDAC[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[3]}]
set_property PACKAGE_PIN T6 [get_ports {toDAC[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[2]}]
set_property PACKAGE_PIN R8 [get_ports {toDAC[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[1]}]
set_property PACKAGE_PIN T8 [get_ports {toDAC[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {toDAC[0]}]

## bluetooth
set_property PACKAGE_PIN N2 [get_ports {butx}]
set_property IOSTANDARD LVCMOS33 [get_ports {butx}]
set_property PACKAGE_PIN L3 [get_ports {burx}]
set_property IOSTANDARD LVCMOS33 [get_ports {burx}]
set_property PACKAGE_PIN D18 [get_ports {bt_pw}]
set_property PACKAGE_PIN M2 [get_ports {bt_rst}]
set_property PACKAGE_PIN E18 [get_ports {bt_sw}]
set_property PACKAGE_PIN H15 [get_ports {bt_sw_hw}]
set_property PACKAGE_PIN C16 [get_ports {bt_master}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt_master}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt_pw}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt_rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt_sw}]
set_property IOSTANDARD LVCMOS33 [get_ports {bt_sw_hw}]

## serial
set_property PACKAGE_PIN T4 [get_ports {sutx}]
set_property IOSTANDARD LVCMOS33 [get_ports {sutx}]
set_property PACKAGE_PIN N5 [get_ports {surx}]
set_property IOSTANDARD LVCMOS33 [get_ports {surx}]
